### ISSUE TITLE
Support for input datasets formatted according to BIDS

### ISSUE THREAD

**Issue by chrisfilo** [mwaskom/lyman#154]
lyman could greatly benefit from supporting input BIDS datasets. This could streamline the input parameters that users need to provide. Judging from the documentation the following parameters and config files could be inferred directly from BIDS formatted datasets:

- `scans.yaml`
- `voxel_size`
- `phase_encoding`
- `scan_info`
- `tr`
- `<model>.csv`

Integration of this feature can be supported by using [BIDSDataGrabber](https://github.com/nipy/nipype/blob/0803819362eef77c469b8dad22b9df81680a4a64/nipype/interfaces/bids_utils.py#L51) (from nipype) and/or the [pybids](https://github.com/INCF/pybids) library.

Adding BIDS support would not only make it easier to run lyman on a growing number of neuroimaging datasets (OpenfMRI, dHCP, SchizConnect, FCP-INDI - mentioning only the public ones) but would also pave the way to hosting on [OpenNeuro.org](http://OpenNeuro.org) as a free cloud data processing service.

**Comment by mwaskom** [comment]
Ok, but I don't really care about any of that. I want to run Lyman on my own datasets on my own cluster. I see no advantages of learning another data layout that may or may not meet all my needs...

**Comment by chrisfilo** [comment]
Fair enough!
