### ISSUE TITLE
data_dictionary definition unclear that lyman requires the output of freesurfer recon-all

### ISSUE THREAD

**Issue by sguthrie** [mwaskom/lyman#164]
Though the following statement implies that Freesurfer recon-all must be run before lyman is run, I found it necessary to build the v1.0.0 documentation to learn what was needed. (In general, I've found the v1.0.0 documentation to be much more helpful than the current build of the docs at [Lyman](http://www.cns.nyu.edu/~mwaskom/software/lyman/index.html)). Is it possible to re-link some of the old documentation to the current documentation, especially because v2.0.0 is not yet released?

_glossary.rst_
    **data_dictionary**
>  "Should also correspond to the Freesurfer SUBJECTS_DIR"

_v1.0.0/workflow.rst_
    **Prepare the Data**
> Lyman also relies on the outputs from Freesurfer. Before using the lyman tools, you should processes 
your anatomical data using recon-all. The lyman data_dir should be synonymous with your Freesurfer $SUBJECTS_DIR, and you should use the same subject ids with both tools.

**Comment by mwaskom** [comment]
[Someone else](https://github.com/mwaskom/lyman/issues/163) is hosting a copy of the v1.0.0 docs, if you'd like to refer to them.

In general v2.0 differs from v1.0 to the extent where they're basically packages, and much of the v1.0 docs would be inaccurate for v2.0.

If you're looking for a more comprehensive and user-friendly processing workflow, I'd recommend [fmriprep](http://fmriprep.readthedocs.io/en/latest/index.html).
