### ISSUE TITLE
anatomy_snapshots.py using increasingly more RAM

### ISSUE THREAD

**Issue by Januzz** [mwaskom/lyman#56]
I'm making snapshots of a huge number of Freesurfer subjects (~1000). Every 100 or so, anatomy_snapshots.py is using so much percent of RAM (over 60%) that the server I am letting it run on becomes very unresponsive (we only have 16GB of RAM), so other people using it cannot work properly anymore and I have to quit and restart the execution of the script.

From monitoring its process with top, it seems as if memory usage is increasing with every subject. Do you have an idea what could be the reason for the accumulating memory use? (I don't use the -noclose flag, if this is important)

**Comment by mwaskom** [comment]
Yeah, there's a memory leak in the surface visualization. It's not 100% clear whether it's a problem in PySurfer (see https://github.com/nipy/PySurfer/issues/91) or in Mayavi itself, but there's no way I know of to avoid it other than to batch running the script.

1000 is a lot of subjects!

**Comment by Januzz** [comment]
Alright, thanks! I didn't see the -subjects flag before, now I split my subjects.txt in files with 30 lines/subjects. That should solve the problem...

Yeah, it's a multi-center structural imaging study...

Thanks!

Am 17.02.2015 um 07:43 schrieb Michael Waskom <notifications@github.com>:
