### ISSUE TITLE
confusing error

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#59]
I'm getting this error when I try to run my model. Preprocessing runs fine for this subject. I also get this error when using "-w model" and "-w preproc model". I'm not sure how to debug from here. Any help would be great. 
![screen shot 2015-05-06 at 3 25 54 pm](https://cloud.githubusercontent.com/assets/5826949/7506718/6ba0c96e-f418-11e4-89fc-9382c74b6e3e.png)

**Comment by mwaskom** [comment]
![screenshot 2015-05-06 19 27 34](https://cloud.githubusercontent.com/assets/315810/7507541/f768c2e6-f425-11e4-92e6-ce0a76de36dd.png)

**Comment by iancballard** [comment]
my bad
