### ISSUE TITLE
issue with run_warp and ANTS

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#60]
running run_warp.py fails after running smoothly for a while. It appears to be looking for a file that ANTS doesn't create:

![screen shot 2015-05-07 at 11 33 34 am](https://cloud.githubusercontent.com/assets/5826949/7522922/2ddcb53a-f4ad-11e4-838c-64b3e563bb65.png)

There are a number of files that ANTS creates, but no ants_Warp file.

![screen shot 2015-05-07 at 11 35 53 am](https://cloud.githubusercontent.com/assets/5826949/7522979/7878400a-f4ad-11e4-8a27-19bd12d7a857.png)

**Comment by mwaskom** [comment]
What version of ants did you install

**Comment by iancballard** [comment]
"0.0.7"

**Comment by mwaskom** [comment]
That looks like the lyman version. I've tested that it works with ants 1.9, but they are notorious for breaking backwards compatability so there are no garuntees it will work with any other version.

**Comment by iancballard** [comment]
Update: it works fine with 1.9. I was running the newest version 2.1

**Comment by mwaskom** [comment]
God I hate ANTs so much.
