### ISSUE TITLE
motion regressors

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#61]
Is there a way to tell lyman not to include motion regressors in the GLM?

**Comment by mwaskom** [comment]
No. Why would you want to do that?

**Comment by iancballard** [comment]
I don't like them. Neither do some FSL people. From the feat manual: You may want to include the head motion parameters (as estimated by MCFLIRT motion correction in the Pre-stats processing) as confound EVs in your model. This can sometimes help remove the residual effects of motion that are still left in the data even after motion correction. This is not strongly recommended as there is still much to learn about residual motion effects; simply adding such confound EVs is quite a simplistic solution. 

It's not that big of a deal though. It shouldn't make a huge difference one way or another...

**Comment by mwaskom** [comment]
That seems to be saying "this may not be the best way to do it, so don't do it at all", which seems like a strange perspective to have.

**Comment by iancballard** [comment]
I dont really understand how they do what they’re supposed to. It seems like you are just screwed with residual motion, unless you do something like MELODIC. Also I think they introduce colinearity in the model which can be problematic.

**Comment by mwaskom** [comment]
IMO, if your motion is correlated with your task regressors, your'e screwed whether or not you include the motion regressors in the model.

In any case, if you don't want them, write your own scripts.
