### ISSUE TITLE
ANTs naming conventions

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#80]
It seems that to use the inverse warp file generated by ANTs with WarpImageMultiTransform, the inverse warpfile must be named 'InverseWarp.nii.gz', or it fails the syntax check. You might consider renaming outputs from inverse_warp to InverseWarp in the next release. Then again, this may not be the case in newer versions of ANTs.

**Comment by mwaskom** [comment]
ANTs is a giant pain in the ass.

**Comment by mwaskom** [comment]
Closing because dropping support for normalization / group analyses
