### ISSUE TITLE
bbregister workflow thought

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#81]
Hey Michael,

I noticed that in your bbregister you first do a rough skullstrip with BET. The default value for the fractional intensity threshold, .5, is in my experience too high for T2 data. It sometimes results in big chunks of PFC getting cut off. I'm getting (very slight) improvements in my registrations if I run it with a lower threshold (.1). 

-Ian

**Comment by mwaskom** [comment]
Closed with changes in #106
