### ISSUE TITLE
"whole_brain" error

### ISSUE THREAD

**Issue by sansplot** [mwaskom/lyman#85]
I believe line 51 of workflows/preproc.py has a line that should be changed if the experiment details dictionary is to match the key expected.

That is, from "whole_brain" to "whole_brain_template".
Or else it complains the module inputs has no output called whole_brain_template

Cheers!

**Comment by mwaskom** [comment]
https://github.com/mwaskom/lyman/blob/master/scripts/run_fmri.py#L90
