### ISSUE TITLE
multiple sessions and field maps

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#90]
Hi Michael,

Am I correct that lyman cannot handle having different field map images for data collected from different sessions from the same subject? If so, any ideas for a solution other than to hack something in the field map code that switches the field map path according to the run number?

-Ian

**Comment by mwaskom** [comment]
Why do you say that? The one time I've used fieldmaps they were run-specific and in an experiment that had multiple sessions per subject.

**Comment by mwaskom** [comment]
Closing as no longer relevant due to work in #106
